// <auto-generated />
using System;
using AdminApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241231114135_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdminApi.Models.Menu.AppMenu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'11', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IconClass")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IsSubMenu")
                        .HasColumnType("int");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MenuTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4298),
                            IconClass = "mdi-menu",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 1,
                            MenuTitle = "Menus",
                            ParentID = 0,
                            SortOrder = 2,
                            URL = ""
                        },
                        new
                        {
                            MenuID = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4306),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "All Menu",
                            ParentID = 1,
                            SortOrder = 0,
                            URL = "/menu"
                        },
                        new
                        {
                            MenuID = 3,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4309),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Menu Group",
                            ParentID = 1,
                            SortOrder = 0,
                            URL = "/menu-group"
                        },
                        new
                        {
                            MenuID = 4,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4311),
                            IconClass = "mdi-account",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 1,
                            MenuTitle = "Users",
                            ParentID = 0,
                            SortOrder = 3,
                            URL = ""
                        },
                        new
                        {
                            MenuID = 5,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4313),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "All User",
                            ParentID = 4,
                            SortOrder = 0,
                            URL = "/users"
                        },
                        new
                        {
                            MenuID = 6,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4316),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Roles",
                            ParentID = 4,
                            SortOrder = 0,
                            URL = "/user-role"
                        },
                        new
                        {
                            MenuID = 7,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4318),
                            IconClass = "mdi-history",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 1,
                            MenuTitle = "Logs",
                            ParentID = 0,
                            SortOrder = 4,
                            URL = ""
                        },
                        new
                        {
                            MenuID = 8,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4320),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Browsing Log",
                            ParentID = 7,
                            SortOrder = 0,
                            URL = "/browse-log"
                        },
                        new
                        {
                            MenuID = 9,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4323),
                            IconClass = "",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Error Log",
                            ParentID = 7,
                            SortOrder = 0,
                            URL = "/error-log"
                        },
                        new
                        {
                            MenuID = 10,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4325),
                            IconClass = "mdi-home",
                            IsActive = true,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Dashboard",
                            ParentID = 0,
                            SortOrder = 1,
                            URL = "/dashboard"
                        },
                        new
                        {
                            MenuID = 11,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4328),
                            IconClass = "mdi-frequently-asked-questions",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "FAQ",
                            ParentID = 0,
                            SortOrder = 5,
                            URL = "/faq"
                        },
                        new
                        {
                            MenuID = 12,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4330),
                            IconClass = "mdi-contacts",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "Contact",
                            ParentID = 0,
                            SortOrder = 6,
                            URL = "/contact"
                        },
                        new
                        {
                            MenuID = 13,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4332),
                            IconClass = "mdi-cog",
                            IsActive = false,
                            IsMigrationData = true,
                            IsSubMenu = 0,
                            MenuTitle = "App Settings",
                            ParentID = 0,
                            SortOrder = 7,
                            URL = "/settings"
                        });
                });

            modelBuilder.Entity("AdminApi.Models.Menu.MenuGroup", b =>
                {
                    b.Property<int>("MenuGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuGroupID"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MenuGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MenuGroupID");

                    b.ToTable("MenuGroup");

                    b.HasData(
                        new
                        {
                            MenuGroupID = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(460),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupName = "Super Admin Group"
                        },
                        new
                        {
                            MenuGroupID = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(477),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupName = "User Group"
                        });
                });

            modelBuilder.Entity("AdminApi.Models.Menu.MenuGroupWiseMenuMapping", b =>
                {
                    b.Property<int>("MenuGroupWiseMenuMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'9', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MenuGroupWiseMenuMappingId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MenuGroupId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("MenuGroupWiseMenuMappingId");

                    b.ToTable("MenuGroupWiseMenuMapping");

                    b.HasData(
                        new
                        {
                            MenuGroupWiseMenuMappingId = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4980),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 2
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4984),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 3
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 3,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4987),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 5
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 4,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4988),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 6
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 5,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4990),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 8
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 6,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4992),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 9
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 7,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4994),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 10
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 8,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4996),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 11
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 9,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(4998),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 12
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 10,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(5000),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            MenuId = 13
                        },
                        new
                        {
                            MenuGroupWiseMenuMappingId = 11,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(5002),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 2,
                            MenuId = 10
                        });
                });

            modelBuilder.Entity("AdminApi.Models.Others.Contacts", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AdminApi.Models.Others.ErrorLog", b =>
                {
                    b.Property<int>("ErrorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ErrorLogId"));

                    b.Property<int?>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("ErrorLogId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AdminApi.Models.Others.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("FaqId");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(6753),
                            Description = "Vue Admin is a single page admin template developed by Vue with .Net core 8 API. It’s covered most common features that you need to start a project.",
                            IsActive = true,
                            IsMigrationData = true,
                            Title = "What are the purposes of this app?"
                        },
                        new
                        {
                            FaqId = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(6758),
                            Description = "The most amazing part of this template is, you have five popular Relational database connectivity options here. You have flexibility to choose Sql server, Mysql, Sqlite, PostgreSql and Oracle 12c+.",
                            IsActive = true,
                            IsMigrationData = true,
                            Title = "Why this app differs from others?"
                        });
                });

            modelBuilder.Entity("AdminApi.Models.Others.SiteSettings", b =>
                {
                    b.Property<int>("SiteSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'2', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SiteSettingsId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<bool>("AllowFaq")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowRightClick")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowWelcomeEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AppBarColor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BodyColor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactUsEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUsTelephone")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUsText")
                        .HasColumnType("longtext");

                    b.Property<string>("CopyRightText")
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultEmail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FaviconPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Feature1Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature1Header")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature1Picture")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Feature2Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature2Header")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature2Picture")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Feature3Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature3Header")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature3Picture")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Feature4Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature4Header")
                        .HasColumnType("longtext");

                    b.Property<string>("Feature4Picture")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FooterColor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FooterFacebook")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterInstagram")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterLinkedin")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterText")
                        .HasColumnType("longtext");

                    b.Property<string>("FooterTwitter")
                        .HasColumnType("longtext");

                    b.Property<string>("ForgetPasswordEmailBody")
                        .HasColumnType("longtext");

                    b.Property<string>("ForgetPasswordEmailHeader")
                        .HasColumnType("longtext");

                    b.Property<string>("ForgetPasswordEmailSubject")
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderColor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HomeBox1Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox1Header")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox2Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox2Header")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox3Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox3Header")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox4Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeBox4Header")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeDetail1")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeDetail2")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeHeader1")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeHeader2")
                        .HasColumnType("longtext");

                    b.Property<string>("HomePicture")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Host")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationText")
                        .HasColumnType("longtext");

                    b.Property<string>("SiteTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WelComeMessage")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("WelcomeEmailBody")
                        .HasColumnType("longtext");

                    b.Property<string>("WelcomeEmailHeader")
                        .HasColumnType("longtext");

                    b.Property<string>("WelcomeEmailSubject")
                        .HasColumnType("longtext");

                    b.HasKey("SiteSettingsId");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            SiteSettingsId = 1,
                            AddedBy = 1,
                            AllowFaq = true,
                            AllowRightClick = true,
                            AllowWelcomeEmail = true,
                            AppBarColor = "#363636",
                            BodyColor = "#F9F9F9",
                            ContactUsEmail = "email@email.com",
                            ContactUsTelephone = "+xx (xx) xxxxx-xxxx",
                            ContactUsText = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste explicabo commodi quisquam asperiores dolore ad enim provident veniam perferendis voluptate, perspiciatis. ",
                            CopyRightText = "© 2024 Copyright Vue Admin",
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(5671),
                            DefaultEmail = "",
                            FaviconPath = "",
                            Feature1Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Feature1Header = "Lorem ipsum",
                            Feature1Picture = "",
                            Feature2Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Feature2Header = "Lorem ipsum",
                            Feature2Picture = "",
                            Feature3Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Feature3Header = "Lorem ipsum",
                            Feature3Picture = "",
                            Feature4Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Feature4Header = "Lorem ipsum",
                            Feature4Picture = "",
                            FooterColor = "#FFFFFF",
                            FooterFacebook = "",
                            FooterInstagram = "",
                            FooterLinkedin = "",
                            FooterText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
                            FooterTwitter = "",
                            ForgetPasswordEmailBody = "Forget Password Body",
                            ForgetPasswordEmailHeader = "Forget Password Header",
                            ForgetPasswordEmailSubject = "Forget Password",
                            HeaderColor = "#F5F5F5",
                            HomeBox1Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            HomeBox1Header = "Lorem ipsum",
                            HomeBox2Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            HomeBox2Header = "Lorem ipsum",
                            HomeBox3Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            HomeBox3Header = "Lorem ipsum",
                            HomeBox4Detail = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                            HomeBox4Header = "Lorem ipsum",
                            HomeDetail1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            HomeDetail2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            HomeHeader1 = "Lorem ipsum dolor sit amet !",
                            HomeHeader2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
                            HomePicture = "",
                            Host = "smtp.gmail.com",
                            IsActive = true,
                            IsMigrationData = true,
                            LogoPath = "",
                            Password = "",
                            Port = 587,
                            RegistrationText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            SiteTitle = "Vue Admin",
                            Version = 1,
                            WelComeMessage = "Hello there,Sign in to start your task!",
                            WelcomeEmailBody = "Welcome Body",
                            WelcomeEmailHeader = "Welcome Header",
                            WelcomeEmailSubject = "Welcome"
                        });
                });

            modelBuilder.Entity("AdminApi.Models.User.LogHistory", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Browser")
                        .HasColumnType("longtext");

                    b.Property<string>("BrowserVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("LogCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LogInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LogOutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("LogHistory");
                });

            modelBuilder.Entity("AdminApi.Models.User.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MenuGroupId")
                        .HasColumnType("int");

                    b.Property<string>("RoleDesc")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(1267),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            UserRoleId = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(1273),
                            IsActive = true,
                            IsMigrationData = true,
                            MenuGroupId = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("AdminApi.Models.User.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ForgetPasswordRef")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMigrationData")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPasswordChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PasswordChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(2856),
                            Email = "admin@vueadmin.com",
                            FullName = "John Doe",
                            IsActive = true,
                            IsMigrationData = true,
                            IsPasswordChange = false,
                            Password = "c7JZ+u1vrHp/FQqdD69JQhBTDoLnCNba6dqVyKpEXu4=",
                            PasswordSalt = "3fdcuIxZk3sdxmjJPM0FuA==",
                            UserRoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            AddedBy = 1,
                            DateAdded = new DateTime(2024, 12, 31, 17, 41, 31, 872, DateTimeKind.Local).AddTicks(2863),
                            Email = "user@vueadmin.com",
                            FullName = "Helen Smith",
                            IsActive = true,
                            IsMigrationData = true,
                            IsPasswordChange = false,
                            Password = "AJNri22q/JA3fbO4m0QIRYxEChegS461t7J1f7C/td8=",
                            PasswordSalt = "gLtMyAEbVeLjZGj312VXyg==",
                            UserRoleId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
